# Generated by Django 5.2.4 on 2025-08-12 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Harvest', models.CharField(max_length=50)),
                ('batch_number', models.CharField(max_length=50)),
                ('date_harvested', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('pack_date', models.DateField()),
                ('Harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest', to='operations.harvest')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='operations.package')),
            ],
        ),
        migrations.CreateModel(
            name='Distpach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=50)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_control', to='operations.package')),
            ],
        ),
        migrations.CreateModel(
            name='Quality_control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='operations.package')),
            ],
        ),
    ]
