# Generated by Django 5.2.5 on 2025-08-26 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quality_control',
            name='harvest',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='Harvest',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Harvest',
        ),
        migrations.AddField(
            model_name='harvest',
            name='phytos',
            field=models.CharField(default='Unnamed Phytos', max_length=50),
        ),
        migrations.AddField(
            model_name='harvest',
            name='total_mites_harvest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='units_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='mites_tube',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='package',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='unit_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='operations.package'),
        ),
        migrations.AlterField(
            model_name='package',
            name='batch_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch', models.IntegerField()),
                ('dispatch_date_time', models.DateTimeField()),
                ('client', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='operations.package')),
            ],
        ),
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_check', models.IntegerField()),
                ('qc_date_time', models.DateTimeField()),
                ('mortality_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contamination', models.TextField()),
                ('pass_fail', models.BooleanField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualitycontrol', to='operations.package')),
            ],
        ),
        migrations.DeleteModel(
            name='Distpach',
        ),
        migrations.DeleteModel(
            name='Quality_control',
        ),
        migrations.AddField(
            model_name='package',
            name='harvest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='operations.harvest'),
        ),
    ]
