# Generated by Django 5.2.5 on 2025-08-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_quality_control_harvest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='unit_size',
            field=models.IntegerField(default=0),
        ),
    ]
